### ISSUE TITLE
License and Registration please

### ISSUE THREAD

**Issue by nathan-weinberg** [Daniel-Pivonka/microeconomics#1]
T4R

**Comment by timflannagan** [comment]
@Daniel-Pivonka ptal asap

**Comment by Daniel-Pivonka** [comment]
this project has been moved to https://github.com/microeconomics

**Comment by timflannagan** [comment]
@Daniel-Pivonka any updates on this?

**Comment by Daniel-Pivonka** [comment]
as stated before this project has been moved to https://github.com/microeconomics
